# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c281fab2db4805f92f9f6cdc74079ab55d2724aacc94f4fd6d891372f828d362db133440be14fdc12cae9527fc4f5801ea3759e315c4a2ecedce142c98baf9db

test:
  secret_key_base: d070eea515239a5d72ac406d3b05e87e64623a488e14b28471e28e84518f16726ef134536e1528aa223193030900bbc92030cdb7354796ed2df1f1798b574a03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
